#!/usr/bin/env bash
# dsh-graph client.js 构建脚本（g-142 模块化重构）
# 将 dsh-graph-host/lib/client/ 目录下的子模块拼接组装为 dsh-graph-host/lib/client.js
#
# 用法：从仓库根目录运行 bash scripts/build-client.sh
#
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="dsh-graph-host/lib/client.js"
MOD="dsh-graph-host/lib/client"

PARTS=(
  "_wrapper-top"
  "constants"
  "helpers"
  "session-hooks"
  "live-panel"
  "supervisor-bar"
  "card"
  "card-drawer"
  "goal-actions"
  "goal-modal"
  "drag-prompts"
  "kanban"
  "plugin"
  "_wrapper-bottom"
)

> "$OUT"
first=true
for part in "${PARTS[@]}"; do
  file="$MOD/${part}.js"
  if [ ! -f "$file" ]; then
    echo "ERROR: 缺少子模块 $file" >&2
    exit 1
  fi
  if [ "$first" = true ]; then
    first=false
    # 在第一个模块的头部注释后添加 generated 标记
    # 假设 _wrapper-top.js 开头有 3 行注释
    head -n 3 "$file" >> "$OUT"
    echo "// ⚠️ GENERATED FILE — DO NOT EDIT DIRECTLY" >> "$OUT"
    echo "// This file is auto-generated by scripts/build-client.sh" >> "$OUT"
    echo "// To modify, edit the source modules in dsh-graph-host/lib/client/*.js" >> "$OUT"
    echo "// and run: bash scripts/build-client.sh" >> "$OUT"
    echo "" >> "$OUT"
    # 跳过前 3 行注释，追加剩余内容
    tail -n +4 "$file" >> "$OUT"
    # 添加空行分隔（与原始文件第 9 行一致）
    echo "" >> "$OUT"
  else
    cat "$file" >> "$OUT"
  fi
done

LINES=$(wc -l < "$OUT")
echo "✅ client.js 已组装完成 ($LINES 行)"
