#!/usr/bin/env bash
# dsh-graph client.js 构建脚本（g-142 模块化重构）
# 将 dsh-graph-host/lib/client/ 目录下的子模块拼接组装为 dsh-graph-host/lib/client.js
#
# 用法：从仓库根目录运行 bash scripts/build-client.sh
#
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="dsh-graph-host/lib/client.js"
MOD="dsh-graph-host/lib/client"

PARTS=(
  "_wrapper-top"
  "constants"
  "helpers"
  "session-hooks"
  "live-panel"
  "supervisor-bar"
  "card"
  "card-drawer"
  "goal-actions"
  "goal-modal"
  "criteria-modal"
  "drag-prompts"
  "version-drawer"
  "kanban"
  "settings-modal"
  "settings"
  "plugin"
  "_wrapper-bottom"
)

# 写入稳定的生成标记 header
cat > "$OUT" << 'EOF'
// ⚠️ GENERATED FILE — DO NOT EDIT DIRECTLY
// This file is auto-generated by scripts/build-client.sh
// To modify, edit the source modules in dsh-graph-host/lib/client/*.js
// and run: bash scripts/build-client.sh
EOF

# 拼接所有模块
for part in "${PARTS[@]}"; do
  file="$MOD/${part}.js"
  if [ ! -f "$file" ]; then
    echo "ERROR: 缺少子模块 $file" >&2
    exit 1
  fi
  cat "$file" >> "$OUT"
done

LINES=$(wc -l < "$OUT")
echo "✅ client.js 已组装完成 ($LINES 行)"
